spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
        use-new-id-generator-mappings: false
  datasource:
    initialization-mode=never:logging:
  level:
    org.hibernate.type: trace
server:
  port : 8081


